sudo: false
language: cpp
before_script: 
  - git submodule update --init --recursive
  - export CXX=`which g++-4.9`
  - export CC=`which gcc-4.9`
  - mkdir build
  - gem install coveralls-lcov
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.12.orig.tar.gz
  - tar xf lcov_1.12.orig.tar.gz
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - g++-4.9 
      - valgrind
      - cmake-data
      - cmake
      - lcov
      - liburiparser-dev
script:
  - make -C lcov-1.12/ install
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON -DMEMORY_CHECK=ON -DWITH_CURL=ON -DWITH_SSL=ON ..
  - make
  - make arg3net-coverage-info
after_success:
  - coveralls-lcov coverage.info
 
